# Generated by Django 4.2.1 on 2025-06-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_listed', models.DateTimeField(auto_now_add=True)),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='albums.card')),
            ],
        ),
    ]
