# Generated by Django 4.2.1 on 2025-06-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_card_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='team',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
