# Generated by Django 4.2.1 on 2025-06-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_card_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='team',
            field=models.CharField(choices=[('BOS', 'Boston Bruins'), ('TOR', 'Toronto Maple Leafs'), ('MTL', 'Montreal Canadiens'), ('CHI', 'Chicago Blackhawks'), ('NYR', 'New York Rangers'), ('LAK', 'Los Angeles Kings'), ('TBL', 'Tampa Bay Lightning'), ('EDM', 'Edmonton Oilers'), ('COL', 'Colorado Avalanche'), ('VGK', 'Vegas Golden Knights')], max_length=3),
        ),
    ]
